name: Firebase Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Login to Firebase
        run: firebase login:ci --interactive

      - name: Build and Deploy
        run: |
          npm install
          npm run build --prod
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
